name: build site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (npm)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.12'

      - name: Cache Julia artifacts & compiled
        uses: actions/cache@v4
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/compiled
            ~/.julia/packages
          key: ${{ runner.os }}-julia-${{ hashFiles('Project.toml','Manifest.toml') }}

      - name: Install deps & ensure OpenSSL_jll
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate(); if !("OpenSSL_jll" in keys(Pkg.dependencies())); Pkg.add("OpenSSL_jll"); end; Pkg.build(); Pkg.precompile()'

      - name: Install highlight.js with npm
        run: npm install highlight.js --no-save

      - name: Build site with Franklin
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate(); include("utils.jl"); using Franklin; optimize()'

      # Optionally add steps to deploy the generated site to GitHub Pages or push __site/_site to gh-pages branch
